version: '3.7'

services:
  gitsignage:
    image: gitsignage:DEVEL
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GITHUB_TOKEN: "top.secret.token"
      REPO_LIST: "ac1ja/gc-1000-gps, FRC-1721/1721-RapidReact"
    restart: "no"
    command: "true"
