version: '3.7'

services:
  gitsignage:
    image: gitsignage:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GITHUB_TOKEN: "top.secret.token"
    restart: "no"
    command: "true"
